### ISSUE TITLE
Why not to support both ESM and CommonJS?

### ISSUE THREAD

**Issue by stepaniukm** [ehmicky/modern-errors#19] opened 2023-02-25 12:12 UTC
Hi! Thanks for your awesome work regarding modern-errors, but I have a one problem with this library. It just doesn't work without ESM completely. I've seen this issue https://github.com/ehmicky/modern-errors/issues/3 and I get your points, but I wonder why it's not possible for a library to support temporarily both CommonJS and ESM. I would love to use this library in my project, but due to it's dependencies it's impossible to migrate towards pure ESM setup. I tried it, but I encounter like infinite flow of bugs in deps. 
![image](https://user-images.githubusercontent.com/28492390/221356198-f6cb34fc-7548-4255-bab7-e74de9557b61.png)
Here is a screenshot from another library that just handles it well.

**Comment by ehmicky** [comment] 2023-02-25 18:20
Hi @stepaniukm,

Thanks for your feedback. However, as you mentioned, this is a duplicate of #3, so the answer to your question is described in that other thread. In particular, [this comment](https://github.com/ehmicky/modern-errors/issues/3#issuecomment-1363433960) and the section called "Double packaging" explains the main problem being providing support for both ESM and CommonJS, but other parts of the thread provide with some additional points.

**Closed by ehmicky** 2023-02-25 18:20 UTC

**Comment by stepaniukm** [comment] 2023-02-25 18:22
Oh f.. I kinda scrolled through and didn't notice your comment about double packaging. Thanks for your answer.
